.TH SDTSDEM2ASC 1
.SH NAME
sdtsdem2asc \- translate USGS SDTS/DEM files into ASCII format for a BRL-CAD DSP
.SH SYNOPSIS
.B sdtsdem2asc
<SDTS CATD module> [...options...]

.SH DESCRIPTION
.I  sdtsdem2asc
translates a USGS SDTS/DEM file into an ASCII format suitable for
converting to a BRL-CAD DSP file.  Run the program with option '--help'
for details.

Then create the dsp file: \'asc2dsp mydem-reversed.asc mydem.dsp\'.

.SH DEPENDENCIES

Note the program requires the GDAL/OGR library available here:

http://gdal.org/index.html

and the BRL-CAD package available here:

http://brlcad.org

It also requires CMake to build.  CMake is available here:

http://cmake.org

.SH BUGS
Send bug reports to the author.

.SH AUTHOR
.I sdtsdem2asc
was written by Tom Browder who can be reached at
<tom.browder@gmail.com>.
